# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

files: |
    (?x)^(
        .*binder
        | .*circleci
        | .*coverage
        | .*github
        | .*gitignore
        | .*in
        | .*toml
        | .*yaml
        | .*yml
        | \.git-blame.*
        | AUTHORS.rst
        | CONTRIBUTING.rst
        | LICENSE
        | Makefile
        | doc
        | examples
        | maint_tools/.*
        | setup.*
        | nilearn/__init__.py
        | nilearn/masking.py
        | nilearn/signal.py
        | nilearn/datasets/.*
        | nilearn/_utils/.*
        | nilearn/de.*
        | nilearn/connectome/.*
        | nilearn/glm/.*
        | nilearn/image/.*
        | nilearn/input_data/.*
        | nilearn/interfaces/.*
        | nilearn/regions/.*
        | nilearn/reporting/.*
        | nilearn/surfaces/.*
        | nilearn/mass_univariate/.*
    )$

exclude: |
    (?x)^(
        nilearn/datasets/tests/data/localizer_behavioural.tsv
        | nilearn/externals/tempita/.*
        | nilearn/_version.py
        | nilearn/_utils/helpers.py
        | nilearn/_utils/docs.py
        | nilearn/_utils/tests/test_data_gen.py
        | nilearn/_utils/data_gen.py
        | nilearn/reporting/html_report.py
        | nilearn/reporting/tests/test_html_report.py
        | nilearn/glm/tests/test_contrasts.py
        | nilearn/glm/contrasts.py
        | nilearn/glm/first_level/first_level.py
        | nilearn/glm/tests/test_second_level.py
        | nilearn/glm/tests/test_first_level.py
        | nilearn/interfaces/__init__.py
        | nilearn/interfaces/fmriprep/__init__.py
        | nilearn/interfaces/bids/__init__.py
        | nilearn/interfaces/fmriprep/load_confounds_components.py
        | nilearn/interfaces/fmriprep/load_confounds_compcor.py
        | nilearn/interfaces/fmriprep/load_confounds_scrub.py
        | nilearn/interfaces/bids/_utils.py
        | nilearn/interfaces/fsl.py
        | nilearn/interfaces/fmriprep/tests/test_load_confounds_scrub.py
        | nilearn/interfaces/fmriprep/tests/test_load_confounds_utils.py
        | nilearn/interfaces/fmriprep/load_confounds_strategy.py
        | nilearn/interfaces/bids/query.py
        | nilearn/interfaces/tests/test_fsl.py
        | nilearn/interfaces/bids/glm.py
        | nilearn/interfaces/fmriprep/tests/test_load_confounds_strategy.py
        | nilearn/interfaces/fmriprep/load_confounds.py
        | nilearn/interfaces/fmriprep/tests/utils.py
        | nilearn/interfaces/fmriprep/load_confounds_utils.py
        | nilearn/interfaces/tests/test_bids.py
        | nilearn/interfaces/fmriprep/tests/test_load_confounds.py
    )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/ikamensh/flynt/
    rev: "0.78"
    hooks:
    -   id: flynt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: [--toml=pyproject.toml]
        additional_dependencies: [tomli]

  - repo: https://github.com/pyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--verbose]
        additional_dependencies: [flake8-docstrings]
