
---
name: Bug report

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to report a bug

title: '[BUG] '

labels: ['bug']

body:

- type: markdown
  attributes:
    value: |
      Provide a brief description of the bug.

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues


- type: checkboxes
  attributes:
    label: Operating system
    description: What operating system are you using?
    options:
    - label: Linux
    - label: Mac
    - label: Windows


- type: textarea
  attributes:
    label: Operating system version
    value: |
      - Linux Ubuntu 18.04 "bionic beaver"
      - Mac OS Version 12 "monterey"
  validations:
    required: false

- type: checkboxes
  attributes:
    label: python version
    description: "What python version are you using?"
    options:
    - label: '3.11'
    - label: '3.10'
    - label: '3.9'
    - label: '3.8'
    - label: '3.7'


- type: dropdown
  attributes:
    label: nilearn version
    description: |
      lorem ipsum
    options:
    - v3.0.0
    - v2.3.0
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe what outcome you expected.
    placeholder: Describe what outcome you expected.
  validations:
    required: false

- type: textarea
  attributes:
    label: Current Behavior & Error message
    description: |
      Describe what you got instead.
      If possible paste below the error message you encountered.
      Also add the error.log that might have been generated.
    value: |
      ```matlab
      % this is the error I got

      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false



# <!--Provide a brief description of the bug.-->


# <!--Please fill in the following information, to the best of your ability.-->
# Nilearn version:


# ### Steps and code to reproduce bug

# <!-- Please ensure the code is a minimal runnable example using Nilearn data to showcase it. -->
# <!-- https://stackoverflow.com/help/minimal-reproducible-example -->

# ```python

# ```
