---
# Workflow to test against the latest nightly releases of development versions of our dependencies
name: test on nightly dependencies

on:

    # commits message must include 'smoke_test' to trigger the workflow on PR
    pull_request:
        branches:
        -   '*'

    schedule:
    # Run every monday at 8am UTC
    -   cron: 0 8 * * 1

    workflow_dispatch:

jobs:
    test_nightly:
        if: ${{ github.repository }} == 'nilearn/nilearn' && contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) || ( github.event_name
            == "pull_request" && contains(github.event.head_commit.message, 'smoke_test') )
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout nilearn
            uses: actions/checkout@v4
        -   name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12
        -   name: install and run ruff checks for NPY NPY201
            # see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin
            run: |
                python -m pip install ruff>0.1.8
                ruff check --preview --select NPY201 .
        -   name: Install tox
            run: python -m pip install tox
        -   name: Run test suite
            id: nightly
            continue-on-error: true
            run: tmp.sh
            #run: tox run -e test_nightly -- nilearn
        -   name: Create issue
            if: steps.nightly.outcome != 'success'
            uses: actions-cool/issues-helper@v3
            with:
                actions: create-issue
                token: ${{ secrets.GITHUB_TOKEN }}
                title: '[BOT] failure of tests on nightly dependencies'
                body: 'test on nightly dependencies failed: @nilearn/core '
