---
# Workflow to test against the latest nightly releases of development versions of our dependencies
name: test on nightly dependencies

on:

    # commits message must include 'smoke_test' to trigger the workflow on PR
    pull_request:
        branches:
        -   '*'

    schedule:
    # Run every monday at 8am UTC
    -   cron: 0 8 * * 1

    workflow_dispatch:

jobs:
    test_nightly:
        if: |
            ${{ github.repository }} == 'nilearn/nilearn' &&
            ( contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) ||
              ( github.event_name == "pull_request" && contains(github.event.head_commit.message, '[test nightly]') )
            )
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout nilearn
            uses: actions/checkout@v4
        -   name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12
        -   name: Install and run ruff checks for NPY NPY201
            # see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin
            continue-on-error: true
            run: |
                python -m pip install ruff>0.1.8
                ruff check --preview --select NPY201 .
        -   name: Install tox
            run: python -m pip install tox
        -   name: Run test suite
            id: nightly
            continue-on-error: true
            run: tox run -e test_nightly -- nilearn
        -   name: Create issue
            if: steps.nightly.outcome != 'success'
            uses: JasonEtco/create-an-issue@v2.9.2
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run_id: ${{ github.run_id }}
                repository: ${{ github.repository }}
            with:
                filename: .github/nightly_failure.md
                update_existing: true
                search_existing: open
        -   name: Return failure
            if: steps.nightly.outcome != 'success'
            run: exit 1
