name: "PEP8"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  pep8:
    runs-on: ubuntu-latest
    name: PEP8 checks
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        name: "Setup python"
      - shell: bash {0}
        run: |
          python -m pip install --upgrade pip flake8
        name: "Install Flake8"
      - shell: bash {0}
        run: ./build_tools/flake8_diff.sh
        name: "Run Flake8 diff"
      - shell: bash {0}
        run: flake8 --config=setup.cfg --verbose "nilearn/decomposition"
        name: "Run Flake8 on whole file"
